// web/src/actions/marginTypes.js
export const FETCH_MARGIN_POSITIONS_REQUEST = 'FETCH_MARGIN_POSITIONS_REQUEST';
export const FETCH_MARGIN_POSITIONS_SUCCESS = 'FETCH_MARGIN_POSITIONS_SUCCESS';
export const FETCH_MARGIN_POSITIONS_FAILURE = 'FETCH_MARGIN_POSITIONS_FAILURE';

export const FETCH_MARGIN_ACCOUNT_BALANCES_REQUEST = 'FETCH_MARGIN_ACCOUNT_BALANCES_REQUEST';
export const FETCH_MARGIN_ACCOUNT_BALANCES_SUCCESS = 'FETCH_MARGIN_ACCOUNT_BALANCES_SUCCESS';
export const FETCH_MARGIN_ACCOUNT_BALANCES_FAILURE = 'FETCH_MARGIN_ACCOUNT_BALANCES_FAILURE';

export const FETCH_MARKET_BORROW_DETAILS_REQUEST = 'FETCH_MARKET_BORROW_DETAILS_REQUEST';
export const FETCH_MARKET_BORROW_DETAILS_SUCCESS = 'FETCH_MARKET_BORROW_DETAILS_SUCCESS';
export const FETCH_MARKET_BORROW_DETAILS_FAILURE = 'FETCH_MARKET_BORROW_DETAILS_FAILURE';

export const TRANSFER_COLLATERAL_FUNDS_REQUEST = 'TRANSFER_COLLATERAL_FUNDS_REQUEST';
export const TRANSFER_COLLATERAL_FUNDS_SUCCESS = 'TRANSFER_COLLATERAL_FUNDS_SUCCESS';
export const TRANSFER_COLLATERAL_FUNDS_FAILURE = 'TRANSFER_COLLATERAL_FUNDS_FAILURE';

export const ADD_POSITION_COLLATERAL_REQUEST = 'ADD_POSITION_COLLATERAL_REQUEST';
export const ADD_POSITION_COLLATERAL_SUCCESS = 'ADD_POSITION_COLLATERAL_SUCCESS';
export const ADD_POSITION_COLLATERAL_FAILURE = 'ADD_POSITION_COLLATERAL_FAILURE';

export const REPAY_POSITION_LOAN_REQUEST = 'REPAY_POSITION_LOAN_REQUEST';
export const REPAY_POSITION_LOAN_SUCCESS = 'REPAY_POSITION_LOAN_SUCCESS';
export const REPAY_POSITION_LOAN_FAILURE = 'REPAY_POSITION_LOAN_FAILURE';

// Used by Trade/index.js to update form values from calculateTrade
// These are not API calls but direct state changes if needed outside redux-form's own state.
// However, redux-form's `change` action creator is typically used directly in components.
// For global state related to trade form if necessary:
// export const SET_MARGIN_TRADE_CALCULATIONS = 'SET_MARGIN_TRADE_CALCULATIONS';
